# Statically link the MSVC C runtime on Windows so the exe doesn't need
# VCRUNTIME140.dll / the VC++ redistributable. An MSIX (Microsoft Store)
# package doesn't bring that runtime with it, and a missing runtime DLL makes
# Windows show an error dialog at launch.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
